all:		trebuchet_v2 trebuchet_v2.c
		@echo "Compiling: trebuchet_v2.c"
		@gcc -Wall -Werror -Wextra -fsanitize=address -g3 trebuchet_v2.c -o trebuchet_v2

clean:
		@rm -rf trebuchet_v2

fclean:		clean

re:			fclean all