all:		cubeconundrum cubeconundrum.cpp
		@echo "Compiling: cubeconundrum.cpp"
		@c++ -Wall -Werror -Wextra -fsanitize=address -g3 cubeconundrum.cpp -o cubeconundrum

clean:
		@rm -rf cubeconundrum

fclean:		clean

re:			fclean all