all:		cubeconundrum_p2 cubeconundrum_p2.cpp
		@echo "Compiling: cubeconundrum_p2.cpp"
		@c++ -Wall -Werror -Wextra -fsanitize=address -g3 cubeconundrum_p2.cpp -o cubeconundrum_p2

clean:
		@rm -rf cubeconundrum_p2

fclean:		clean

re:			fclean all